version: '3.8'  # Update version (or remove it as suggested by warning)

services:
  catalog1:
    build:
      context: ./catalog  # Changed to match your folder structure
    ports:
      - "2001:2001"
    environment:
    - REPLICA_URL=http://catalog2:2001
    networks:
      - bazarcom-network
  catalog2:
    build: ./catalog
    ports:
      - "2003:2001"
    environment:
    - REPLICA_URL=http://catalog1:2001
    networks:
      - bazarcom-network
  order1:
    build:
      context: ./order
    ports:
      - "2002:2002"
    environment:
      - REPLICA_URL=http://order2:2002
    networks:
      - bazarcom-network
  order2:
    build: ./order
    ports:
      - "2004:2002"
    environment:
      - REPLICA_URL=http://order1:2002
    networks:
      - bazarcom-network
  frontend:
    build:
      context: ./frontend
    ports:
      - "2000:2000"
    networks:
      - bazarcom-network
    depends_on:
      - catalog1
      - catalog2
      - order1
      - order2

networks:
  bazarcom-network:
    driver: bridge